version: "3.8"

services:
  # 1. The Database
  postgres:
    image: "postgres:16"
    container_name: spotify_postgres
    environment:
      - "POSTGRES_DB=spotify_analytics"
      - "POSTGRES_PASSWORD=mypassword"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Zookeeper (Required manager for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: spotify_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 3. Apache Kafka (The Event Bus)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: spotify_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # IMPORTANT: This tells Kafka "If you are inside Docker, use port 29092. If you are outside (Java App), use localhost:9092"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
